execution:
  algorithm: smart
  order_types:
    post_only: false
    use_limit_orders: false
    use_market_orders: true
  retry:
    backoff_seconds: 1
    max_attempts: 3
logging:
  backup_count: 5
  file: logs/quantum_trading.log
  level: INFO
  max_size: 10485760
redis:
  db: 0
  host: localhost
  port: 6379
risk_management:
  enabled: true
  limits:
    emergency_stop_percent: 1.5
    max_daily_loss_percent: 2.0
    max_drawdown_percent: 5.0
    max_monthly_loss_percent: 10.0
    max_weekly_loss_percent: 5.0
  position_sizing:
    kelly_fraction: 0.25
    max_position_percent: 30
    method: kelly
strategies:
  ai_prediction:
    enabled: true
    params:
      max_position_percent: 10
      min_confidence: 0.6
      model_path: models/rf_model.pkl
      retrain_interval: 24
    weight: 0.05
  market_making:
    enabled: true
    params:
      inventory_limit: 1000000
      order_layers: 5
      spread_threshold: 0.0002
    weight: 0.3
  mean_reversion:
    enabled: true
    params:
      bb_period: 20
      bb_std: 1.5
      rsi_overbought: 70
      rsi_oversold: 30
      rsi_period: 14
    weight: 0.15
  microstructure:
    enabled: true
    params:
      flow_window: 100
      vwap_deviation_threshold: 0.001
    weight: 0.2
  momentum_scalping:
    enabled: true
    params:
      entry_threshold: 0.001
      momentum_period: 20
      stop_loss: 0.003
      take_profit: 0.002
    weight: 0.15
  statistical_arbitrage:
    enabled: true
    params:
      entry_zscore: 1.2
      exit_zscore: 0.3
      lookback_period: 100
    weight: 0.15
system:
  environment: production
  name: Quantum Trading System
  timezone: Asia/Seoul
  version: 3.0.0
trading:
  base_currency: KRW
  enabled: true
  interval: 60
  limits:
    max_open_orders: 10
    max_order_size: 500000
    max_position: 10000000
    min_order_size: 5000
  mode: dry_run
  quote_currency: BTC
  signal_threshold: 0.01
  symbol: KRW-BTC
